### PR TITLE
compass chart available prop added

### PR DESCRIPTION
**Pull request by frusciante189**

### CODE REVIEW

**Comment by ma9o** [comment]
@frusciante189 Could you move this logic to a more generic component that can be reused across all charts?

**Comment by ma9o** [comment]
Also would be cool to display "Unavailable" on top of the chart, at the center, on top of a white card:

image

**Comment by frusciante189** [comment]
Something like that?

Screenshot 2024-04-09 at 02 04 51

**Comment by ma9o** [comment]
I'm gonna change the style a bit

**Comment by ma9o** [comment]
I've cherry picked your commits into dev directly because the branch got out of sync

**Pull request closed without merging**
